blueprint:
  name: Homematic keypress -> toggle light
  description: If a Homematic key is pressed, toggle selected light
  domain: automation
  source_url: https://github.com/FreeTimeCoder82/home-assistant-blueprints/blob/dev/homematic_keypress_toggle_light.yaml
  input:
    channel:
      name: Channel of the switch
      description: Channel of the switch
      default: 1
      selector:
        number:
          min: 1
          max: 6
          mode: slider
          step: 1
    serialnumber:
      name: Serialnumber of the switch
      selector:
        text:
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light

trigger:
  - platform: event
    event_type: homematic.keypress
    event_data:
      name: !input serialnumber
      channel: !input channel
      param: PRESS_SHORT

action:
  - service: light.toggle
    target: !input light_target
